export { default as Home } from './Home'
export { default as Shop } from './Shop'
export { default as Product } from './Product'
export { default as Blogs } from './Blogs'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Layout } from './Layout'
